<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>

    <!-- NativeAOT configuration -->
    <PublishAot>true</PublishAot>
    <OptimizationPreference>Size</OptimizationPreference>
    <XmlResolverIsNetworkingEnabledByDefault>false</XmlResolverIsNetworkingEnabledByDefault>

    <!-- Generate information for sizoscope -->
    <IlcGenerateMstatFile>true</IlcGenerateMstatFile>
    <IlcGenerateDgmlFile>true</IlcGenerateDgmlFile>

    <!-- Generates the cabinet.h C-header file -->
    <GenerateCabinet>true</GenerateCabinet>
  </PropertyGroup>

  <!-- Embedding the file as an EmbeddedResource only allows targetting the current assembly,
       therefore we need to use the substitution Ilc argument, targetting the whole compilation. -->
  <ItemGroup>
    <IlcArg Include="--substitution:$(MSBuildThisFileDirectory)ILLink.Substitutions.xml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\osu.Native.Analyzers\osu.Native.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="cabi.net" Version="0.0.6" />
    <PackageReference Include="ppy.osu.Game" Version="2025.1029.0" />
    <PackageReference Include="ppy.osu.Game.Rulesets.Catch" Version="2025.1029.0" />
    <PackageReference Include="ppy.osu.Game.Rulesets.Mania" Version="2025.1029.0" />
    <PackageReference Include="ppy.osu.Game.Rulesets.Osu" Version="2025.1029.0" />
    <PackageReference Include="ppy.osu.Game.Rulesets.Taiko" Version="2025.1029.0" />
    <PackageReference Include="ppy.osu.Game.Resources" Version="*">
      <ExcludeAssets>all</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="Exists('../osu.Game')">
    <PackageReference Include="cabi.net" Version="0.0.6" />
    <ProjectReference Include="../osu.Game/osu.Game/osu.Game.csproj" />
    <ProjectReference Include="../osu.Game/osu.Game.Rulesets.Catch/osu.Game.Rulesets.Catch.csproj" />
    <ProjectReference Include="../osu.Game/osu.Game.Rulesets.Mania/osu.Game.Rulesets.Mania.csproj" />
    <ProjectReference Include="../osu.Game/osu.Game.Rulesets.Osu/osu.Game.Rulesets.Osu.csproj" />
    <ProjectReference Include="../osu.Game/osu.Game.Rulesets.Taiko/osu.Game.Rulesets.Taiko.csproj" />
    <PackageReference Include="ppy.osu.Game.Resources" Version="*">
      <ExcludeAssets>all</ExcludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
